dualarm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  computedtorque_control_clik:
    type: dualarm_controller/ComputedTorque_Control_CLIK
    joints:
      - dualarm_joint1
      - dualarm_joint2
      - dualarm_joint3
      - dualarm_joint4
      - dualarm_joint5
      - dualarm_joint6
      - dualarm_joint7
      - dualarm_joint8
      - dualarm_joint9
      - dualarm_joint10
      - dualarm_joint11
      - dualarm_joint12
      - dualarm_joint13
      - dualarm_joint14

    gains:
      dualarm_joint1:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint2:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint3:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint4:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint5:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint6:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint7:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint8:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint9:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint10:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint11:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint12:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint13:
        pid: {p: 20.0, i: 100.0, d: 1.0}
      dualarm_joint14:
        pid: {p: 20.0, i: 100.0, d: 1.0}


    root_link: world
    tip_link1: link_08
    tip_link2: link_14

    ctr_obj: 1

    ik_mode: 2

    clik_gain: {K_regulation: 6.0, K_tracking: 1.0}